# Generated by Django 5.2.5 on 2025-08-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_alter_favorite_unique_together_blog_category_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorite",
            name="unique_user_blog_favorite",
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together=set(),
        ),
    ]
