# Generated by Django 5.2.5 on 2025-08-26 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_codeanalysis_analysisissue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codeanalysis",
            options={},
        ),
        migrations.RenameField(
            model_name="favorite",
            old_name="added_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="analysisissue",
            name="title",
        ),
        migrations.RemoveField(
            model_name="codeanalysis",
            name="analysis_result",
        ),
        migrations.RemoveField(
            model_name="codeanalysis",
            name="user_ip",
        ),
        migrations.AddField(
            model_name="codeanalysis",
            name="ai_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codeanalysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="analysisissue",
            name="issue_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="analysisissue",
            name="line_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysisissue",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="analysisissue",
            name="suggestion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="codeanalysis",
            name="filename",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="codeanalysis",
            name="language",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="codeanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blogapp.blog"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "blog")},
        ),
    ]
