# Generated by Django 5.2.5 on 2025-08-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_alter_codeanalysis_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("Technology", "Technology"),
                    ("Programming", "Programming"),
                    ("Tutorial", "Tutorial"),
                    ("Review", "Review"),
                    ("News", "News"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
